language: ruby
before_install:
 - sudo apt-get install libpcap-dev -qq
before_script:
 - travis_retry gem update bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head
env:
  rvmsudo_secure_path: 1
cache: bundler
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script:
  - rvmsudo bundle exec rake
