language: ruby
before_install:
 - sudo apt-get install libpcap-dev -qq
before_script:
 - travis_retry gem update bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script:
  - rvmsudo bundle exec rake
